server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: "*"


resilience4j:
  retry:
    instances:
      productservice:
        maxAttempts: 5
        waitDuration: 2s